[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sportsbook = "37x9AGp1ipgNfGbuoEVxQtjT5RJnJss6pT3V49TDnm5p"

[programs.localnet]
sportsbook = "37x9AGp1ipgNfGbuoEVxQtjT5RJnJss6pT3V49TDnm5p"

[programs.mainnet]
sportsbook = "Spo7t11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.ankr.com/solana_devnet"
wallet = "/home/user/phantomzero-vrf/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
